In [8]:
import cv2
img=cv2.imread('0.jpeg')
# initilization of window
cv2.namedWindow('IMAGE',0)

cv2.imshow('IMAGE',img)
cv2.imwrite('output.jpeg',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
#access and understand pixel data
import cv2
import numpy as np
img=cv2.imread('0.jpeg')

print(img)
print(type(img))
print(len(img))
print(len(img[0]))
print(len(img[0][0]))
print(img.shape)
print(img.dtype)
print(img[:,:,0])      #red channel
print(img[10][15])


[[[ 24 146 162]
  [ 21 146 166]
  [ 16 147 174]
  ...
  [  7 146 172]
  [ 16 149 169]
  [ 23 155 172]]

 [[ 24 151 166]
  [ 22 151 170]
  [ 15 151 177]
  ...
  [  7 151 176]
  [ 13 152 171]
  [ 17 156 172]]

 [[ 22 159 175]
  [ 19 158 177]
  [ 14 157 184]
  ...
  [ 13 165 189]
  [ 14 164 181]
  [ 17 166 180]]

 ...

 [[  6 176 194]
  [  2 174 192]
  [  8 179 201]
  ...
  [  1 186 196]
  [  0 183 188]
  [  0 175 178]]

 [[  0 167 185]
  [  0 167 185]
  [  0 168 191]
  ...
  [  0 177 188]
  [  0 180 188]
  [  0 180 186]]

 [[  0 162 180]
  [  0 163 181]
  [  0 161 184]
  ...
  [  0 168 182]
  [  0 173 183]
  [  0 181 189]]]
<class 'numpy.ndarray'>
920
752
3
(920, 752, 3)
uint8
[[24 21 16 ...  7 16 23]
 [24 22 15 ...  7 13 17]
 [22 19 14 ... 13 14 17]
 ...
 [ 6  2  8 ...  1  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
[ 86 162 214]


In [15]:
# Data types and structures
import numpy as np
import cv2

black=np.zeros([150,150,1],'uint8')
cv2.imshow('black',black)
print(black[0,0,:])

ones=np.ones([150,150,3],'uint8')
# ones*=(2**8-1)
cv2.imshow('ones',ones)
print(ones[0,0,:])

white=np.ones([150,150,3],'uint16')
white*=(2**16-1)
cv2.imshow('white',white)
print(white[0,0,:])

#
color=ones.copy()
color[:,:]=(255,0,0) #blue
cv2.imshow('blue',color)
print(color[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[0]
[1 1 1]
[65535 65535 65535]
[255   0   0]


In [17]:
# image types and color channels
import numpy as np
import cv2
img=cv2.imread('0.jpeg',1)
cv2.imshow('image',img)
cv2.moveWindow('image',0,0)

print(img.shape)
width,height,channel=img.shape

cv2.waitKey(0)
cv2.destroyAllWindows()

(920, 752, 3)


In [7]:
# pixel manipulation and filtering
import cv2
img=cv2.imread('0.jpeg',1)

gray=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
cv2.imshow('KESHAV',gray)

r=img[:,:,0]
g=img[:,:,1]
b=img[:,:,2]

rgba=cv2.merge((r,g,b,g))
cv2.imshow('rgba',rgba)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# Gussian Blur,dilation and erosion
import numpy as np
import cv2
img=cv2.imread('0.jpeg',1)
cv2.imshow('original',img)

# blur
blur=cv2.GaussianBlur(img,(5,55),0)
cv2.imshow('Gaussian Blur',blur)

kernel=np.ones((5,5),'uint8')
dilate=cv2.dilate(img,kernel,iterations=1)
erode=cv2.erode(img,kernel,iterations=1)

cv2.imshow('dilate',dilate)
cv2.imshow('erode',erode)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# scale and rotate image
import numpy as np
import cv2
img=cv2.imread('0.jpeg',1)
cv2.imshow('original',img)

# scale
half=cv2.resize(img,(0,0),fx=0.5,fy=0.5,)
cv2.imshow('half',half)

stretch_=cv2.resize(img,(600,600),fx=0.5,fy=0.5)
cv2.imshow('stretch_',stretch_)

stretch_near_=cv2.resize(img,(600,600),fx=0.5,fy=0.5,interpolation = cv2.INTER_NEAREST)
cv2.imshow('stretch_near_',stretch_near_)

# rotate
M=cv2.getRotationMatrix2D((0,0),-30,1)
rotated=cv2.warpAffine(img,M,(img.shape[1],img.shape[0]))
cv2.imshow('rotated',rotated)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# video inputs
import numpy as np
import cv2
cap=cv2.VideoCapture(0)
while True:
    ret,frame=cap.read()
    cv2.imshow('keshav',frame)
    if cv2.waitKey(1)&0xff==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [3]:
# create custom interface
import numpy as np
import cv2
cap=cv2.VideoCapture(0)
# circle
color=(0,255,0)
point=(200,200)
radius=40
border_width=6

while True:
    ret,frame=cap.read()
    cv2.circle(frame,point,radius,color,border_width)
    cv2.imshow('keshav',frame)
    if cv2.waitKey(1)&0xff==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
cap=cv2.VideoCapture(0)
# circle
color=(0,255,0)
point=(200,200)
radius=40
border_width=6
def click(event,x,y)
while True:
    ret,frame=cap.read()
    cv2.circle(frame,point,radius,color,border_width)
    cv2.imshow('keshav',frame)
    if cv2.waitKey(1)&0xff==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()