n=

### String:

In [23]:
str_ = "Keshav"
str_

'Keshav'

### Stack:

In [17]:
from queue import LifoQueue
st = LifoQueue()
st.put('a') #insert
st.put('c')
st.put('d')

In [18]:
st.get() #pop

'd'

### Queue:

In [19]:
from queue import Queue
q = Queue()
q.put('a')
q.put('c')
q.put('d')

In [20]:
q.get()

'a'

### Dynamic array:

In [22]:
import numpy as np
v=np.array([], dtype=np.int)
v=np.append(v,[2])
v=np.append(v,[45])
v=np.append(v,[67])
v

array([ 2, 45, 67])

### Sort: 

In [23]:
v.sort()
v

array([ 2, 45, 67])

In [24]:
v[::-1].sort()
v

array([67, 45,  2])

### Searching: (Binary search with sorted array)

In [37]:
k=v
k

array([67, 45,  2])

In [38]:
np.searchsorted([12,23,34,45,56,67,78],45)

3

In [39]:
np.searchsorted([12,23,34,45,56,67,78],45,side='right')

4

### Map: 
- Creating pairs like roll_number with name {23, Ram}, {24, Alex}, etc.

In [41]:
mp = { 23 : "Ram", 24 : "Alex"}
mp

{23: 'Ram', 24: 'Alex'}

### Set: 
- It eliminates duplicate entry.

In [42]:
s = set()
s.add(56)
s.add(65)
s

{56, 65}