In [1]:
import collections as c

In [3]:
print(c.__doc__)

This module implements specialized container datatypes providing
alternatives to Python's general purpose built-in containers, dict,
list, set, and tuple.

* namedtuple   factory function for creating tuple subclasses with named fields
* deque        list-like container with fast appends and pops on either end
* ChainMap     dict-like class for creating a single view of multiple mappings
* Counter      dict subclass for counting hashable objects
* OrderedDict  dict subclass that remembers the order entries were added
* defaultdict  dict subclass that calls a factory function to supply missing values
* UserDict     wrapper around dictionary objects for easier dict subclassing
* UserList     wrapper around list objects for easier list subclassing
* UserString   wrapper around string objects for easier string subclassing




In [5]:
x="KeshavSingh"
for i in x:
    print(i)

K
e
s
h
a
v
S
i
n
g
h


In [6]:
x=c.Counter("KeshavSingh")
for i in x.elements():
    print(i)

K
e
s
h
h
a
v
S
i
n
g


In [9]:
import sys
import numpy as np
l=[1,2,3,4,5]
print(sys.getsizeof(l))

112


In [20]:
a=np.array(l)
print(sys.getsizeof(0))

24


# Nd-Array

In [37]:
a=np.array([0,127,128],np.int8)

In [38]:
a

array([   0,  127, -128], dtype=int8)

In [39]:
sys.getsizeof(a)

99

In [40]:
a=np.array([0,127,128],np.int16)

In [41]:
a

array([  0, 127, 128], dtype=int16)

In [42]:
sys.getsizeof(a)

102

In [44]:
for i in a:
    print(i)

0
127
128


In [46]:
a=np.array([0,127,128],dtype='int8')

In [47]:
a

array([   0,  127, -128], dtype=int8)

In [48]:
a=[1,3,2,4,5,6]
b=[3,4,5]
np.may_share_memory(b,a)

False

In [49]:
np.may_share_memory(a,b)

False

In [66]:
np.shape([[3,4,5],[5,6,7],[3,4,5],[3,4,5]])

(4, 3)

In [67]:
a=[[3,4,5],[5,6,7],[3,4,5],[3,4,5]]

In [74]:
b=np.shape(a)
print(b)

(4, 3)


In [75]:
c=np.arange(12)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [76]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
np.may_share_memory(c,b)

False

In [82]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [83]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [86]:
l=[2,3,4,5,7,8]

In [87]:
np.ones_like(l)

array([1, 1, 1, 1, 1, 1])

In [89]:
np.zeros_like(l)

array([0, 0, 0, 0, 0, 0])

In [91]:
np.zeros_like(45)

array(0)

In [92]:
np.zeros_like('r')

array('', dtype='<U1')

In [97]:
np.array(123,dtype='<U1')

array('1', dtype='<U1')

In [98]:
np.array(123,dtype='<U2')

array('12', dtype='<U2')

In [99]:
np.array(123,dtype='<U3')

array('123', dtype='<U3')

In [101]:
a=l[:3]

In [103]:
np.may_share_memory(l,a)

False

In [116]:
dt=np.dtype([('Roll',np.int16),('Name','S20'),('CS','S15')])

In [118]:
np.array([(123,),('Keshav',),('CSE',)],dtype=dt)

ValueError: could not assign tuple of length 1 to structure with 3 fields.

In [122]:
a=np.array([[3,4],[2,6]])

In [123]:
b=np.array([[1,2],[3,4]])

In [124]:
#Matrix Multiplication
a.dot(b)

array([[15, 22],
       [20, 28]])