In [2]:
import numpy as np

In [2]:
np.log(12)

2.4849066497880004

In [3]:
np.log10(12)

1.0791812460476249

In [5]:
np.log2(12)

3.584962500721156

In [8]:
np.pi

3.141592653589793

In [9]:
np.e

2.718281828459045

In [10]:
np.log(np.e)

1.0

In [1]:
a=[[1,2],[3,4],[6,5]]

In [22]:
b=[[3,4],[6,1],[6,8]]

In [23]:
a.dot(b)

AttributeError: 'list' object has no attribute 'dot'

In [24]:
a=np.array(a)
b=np.array(b)

In [25]:
a.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [3]:
np.transpose(a)

array([[1, 3, 6],
       [2, 4, 5]])

In [4]:
a.T

AttributeError: 'list' object has no attribute 'T'

In [5]:
a=[1,2]
a1=np.array(a)

In [12]:
a2=np.array([2,1])

In [13]:
a1*a2

array([2, 2])

# Dot Product

In [14]:
# 1st method
np.sum(a1*a2)

4

In [15]:
# 2nd method
(a1*a2).sum()

4

In [28]:
# 3rd method
dot=0
for i,j in zip(a1,a2):
    dot+=i*j
print(dot)

4


In [29]:
# 4th method
np.dot(a1,a2)

4

In [31]:
a1.dot(a2)

4

In [32]:
a2.dot(a1)

4

###  mode of matrix or 

In [33]:
amag=np.sqrt((a1*a1).sum())

In [34]:
amag

2.23606797749979

In [37]:
amagb=np.linalg.norm(a1)

In [38]:
amag

2.23606797749979

In [39]:
cosangle=(a1*a2).sum()/(np.linalg.norm(a1)*np.linalg.norm(a2))

In [40]:
cosangle

0.7999999999999998

In [45]:
angle=np.arccos(cosangle)

In [46]:
angle

0.6435011087932847

# Speed Comparision

In [47]:
from datetime import datetime as dt

In [59]:
a=np.random.randn(100)
b=np.random.randn(100)
T=100000

def slow_ab(a,b):
    result=0
    for i,j in zip(a,b):
        result+=i*j
    return result
t0=dt.now()
for t in range(T):
    slow_ab(a,b)
dt1=dt.now()-t0

t0=dt.now()
for t in range(T):
    a.dot(b)
dt2=dt.now()-t0

print('dt1/dt2 : ',dt1/dt2)

dt1/dt2 :  42.67074159343688


In [82]:
dt1.total_seconds()/dt2.total_seconds()

42.67074159343688

### vectors and matrices

In [88]:
l=[[1,2,3],[4,5]]
m=np.array(l)

In [89]:
l[0][0]

1

In [90]:
l[0,0]

TypeError: list indices must be integers or slices, not tuple

In [91]:
m[0][0]

1

In [92]:
m[0,0]

IndexError: too many indices for array

In [93]:
l

[[1, 2, 3], [4, 5]]

In [94]:
m

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [96]:
M=np.matrix(l)

In [97]:
M

matrix([[list([1, 2, 3]), list([4, 5])]], dtype=object)

In [99]:
a=np.array(M)

In [100]:
a

array([[list([1, 2, 3]), list([4, 5])]], dtype=object)

In [101]:
a.T

array([[list([1, 2, 3])],
       [list([4, 5])]], dtype=object)

In [103]:
# 

In [105]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [108]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [109]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [110]:
np.random.random(10)

array([0.62770771, 0.72841671, 0.20794275, 0.89594748, 0.47620957,
       0.33335071, 0.15777927, 0.05193425, 0.31241391, 0.90510364])

In [111]:
np.random.random((10,10))

array([[0.36338446, 0.2244167 , 0.80886067, 0.79517863, 0.86917291,
        0.9310525 , 0.7934511 , 0.15356517, 0.81629119, 0.55649162],
       [0.02775134, 0.45178623, 0.96230507, 0.92341694, 0.51190785,
        0.49155864, 0.10183091, 0.82071166, 0.6551772 , 0.99671401],
       [0.65806974, 0.92522901, 0.91920264, 0.60051165, 0.08825201,
        0.68488935, 0.68948749, 0.25342272, 0.42922668, 0.54489604],
       [0.65534169, 0.06913586, 0.40203202, 0.59014047, 0.29452973,
        0.44882698, 0.89624587, 0.20310985, 0.4579726 , 0.63151472],
       [0.30176137, 0.75848191, 0.18777294, 0.23472855, 0.58245908,
        0.15099148, 0.45833776, 0.39879711, 0.993903  , 0.87164769],
       [0.60907759, 0.8855197 , 0.89096846, 0.73350982, 0.97832344,
        0.76697343, 0.28083786, 0.96710881, 0.95973318, 0.13179614],
       [0.1500974 , 0.88792455, 0.87791346, 0.45975058, 0.15027404,
        0.39737921, 0.10848364, 0.22267496, 0.2545876 , 0.98476586],
       [0.89825452, 0.80056813, 0.7552797

In [112]:
np.random.random((10,10)).mean()

0.4854564943631645

In [113]:
np.random.random((10,10)).sum()

47.18315661341966

# Matrix

In [2]:
import numpy as np
dir(np.linalg)

['LinAlgError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'absolute_import',
 'cholesky',
 'cond',
 'det',
 'division',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'info',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'print_function',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [3]:
a=[[1,3],[4,6]]

In [4]:
an=np.linalg.inv(a)

In [5]:
a

[[1, 3], [4, 6]]

In [6]:
an

array([[-1.        ,  0.5       ],
       [ 0.66666667, -0.16666667]])

In [11]:
np.dot(a,an)

array([[1., 0.],
       [0., 1.]])